// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia;

public partial class AuditoriaCambios
{
    public int Id { get; set; }

    public string Usuario { get; set; }

    public string Accion { get; set; }

    public string EventoRealizado { get; set; }

    public string Modulo { get; set; }

    public string Fecha { get; set; }

    public string Ip { get; set; }

    public string UsuarioAfectado { get; set; }
}