// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia;

public partial class BCPSistemaVigilanciaContext : DbContext
{
    public BCPSistemaVigilanciaContext(DbContextOptions<BCPSistemaVigilanciaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditoriaCambios> AuditoriaCambios { get; set; }

    public virtual DbSet<AuditoriaError> AuditoriaError { get; set; }

    public virtual DbSet<AuditoriaIngreso> AuditoriaIngreso { get; set; }

    public virtual DbSet<Grupo> Grupo { get; set; }

    public virtual DbSet<Modulo> Modulo { get; set; }

    public virtual DbSet<ModuloPermiso> ModuloPermiso { get; set; }

    public virtual DbSet<NivelAlarma> NivelAlarma { get; set; }

    public virtual DbSet<PermisoGrupo> PermisoGrupo { get; set; }

    public virtual DbSet<TipoAlarma> TipoAlarma { get; set; }

    public virtual DbSet<UsuariosConectado> UsuariosConectado { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditoriaCambios>(entity =>
        {
            entity.ToTable("Auditoria_Cambios");

            entity.Property(e => e.Accion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EventoRealizado)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("Evento_Realizado");
            entity.Property(e => e.Fecha)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Ip)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Modulo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Usuario)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UsuarioAfectado)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AuditoriaError>(entity =>
        {
            entity.ToTable("Auditoria_Error");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AuditoriaIngreso>(entity =>
        {
            entity.ToTable("Auditoria_Ingreso");

            entity.Property(e => e.Accion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EventoRealizado)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Evento_Realizado");
            entity.Property(e => e.Fecha)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Ip)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Modulo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Usuario)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Grupo>(entity =>
        {
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Modulo>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ModuloPermiso>(entity =>
        {
            entity.ToTable("Modulo_Permiso");
        });

        modelBuilder.Entity<NivelAlarma>(entity =>
        {
            entity.ToTable("Nivel_Alarma");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.NombreNivelAlarma)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PermisoGrupo>(entity =>
        {
            entity.ToTable("Permiso_Grupo");

            entity.Property(e => e.ModuloId).HasColumnName("ModuloID");
        });

        modelBuilder.Entity<TipoAlarma>(entity =>
        {
            entity.ToTable("Tipo_Alarma");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.NombreTipoAlarma)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UsuariosConectado>(entity =>
        {
            entity.HasKey(e => e.Usuario);

            entity.Property(e => e.Usuario)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.Grupo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Ip)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UltimaConsulta).HasColumnType("datetime");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}