// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia;

public partial class Grupo
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public bool? Activo { get; set; }
}