// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia
{
    public partial interface IBCPSistemaVigilanciaContextProcedures
    {
        Task<int> AgregarUsuarioConectadoAsync(string Usuario, DateTime? FechaIngreso, string Ip, DateTime? UltimaConsulta, string Grupo, bool? Estado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ModificarUsuarioConectadoAsync(string Usuario, DateTime? FechaIngreso, string Ip, DateTime? UltimaConsulta, string Grupo, bool? Estado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
