// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia;

public partial class ModuloPermiso
{
    public int Id { get; set; }

    public int? ModuloId { get; set; }

    public int? PermisoId { get; set; }

    public bool? Estado { get; set; }
}