// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia;

public partial class PermisoGrupo
{
    public int Id { get; set; }

    public int? GrupoId { get; set; }

    public int? ModuloId { get; set; }

    public bool? PuedeIngresar { get; set; }
}