// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIBCPSistemaVigilancia.Models.BDBCPSistemaVigilancia;

public partial class UsuariosConectado
{
    public string Usuario { get; set; }

    public DateTime? FechaIngreso { get; set; }

    public string Ip { get; set; }

    public DateTime? UltimaConsulta { get; set; }

    public string Grupo { get; set; }

    public bool? Estado { get; set; }
}