// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace VideovigilanciaDB.Models.VideovigilanciaBCP;

public partial class videovigilanciaBCPContext : DbContext
{
    public videovigilanciaBCPContext(DbContextOptions<videovigilanciaBCPContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AlarmaAnalitica> AlarmaAnalitica { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AlarmaAnalitica>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AlarmaAn__3213E83FA1E36BDC");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AlarmCategory)
                .HasMaxLength(50)
                .HasColumnName("alarmCategory");
            entity.Property(e => e.AlarmDesc)
                .HasMaxLength(100)
                .HasColumnName("alarmDesc");
            entity.Property(e => e.AlarmEventId).HasColumnName("alarmEventId");
            entity.Property(e => e.AlarmInCode)
                .HasMaxLength(255)
                .HasColumnName("alarmInCode");
            entity.Property(e => e.AlarmInName)
                .HasMaxLength(100)
                .HasColumnName("alarmInName");
            entity.Property(e => e.AlarmInType).HasColumnName("alarmInType");
            entity.Property(e => e.AlarmLevelColor)
                .HasMaxLength(100)
                .HasColumnName("alarmLevelColor");
            entity.Property(e => e.AlarmLevelName)
                .HasMaxLength(100)
                .HasColumnName("alarmLevelName");
            entity.Property(e => e.AlarmLevelValue).HasColumnName("alarmLevelValue");
            entity.Property(e => e.AlarmStatus).HasColumnName("alarmStatus");
            entity.Property(e => e.AlarmType)
                .HasMaxLength(100)
                .HasColumnName("alarmType");
            entity.Property(e => e.AlarmTypeName)
                .HasMaxLength(100)
                .HasColumnName("alarmTypeName");
            entity.Property(e => e.ExistsRecord).HasColumnName("existsRecord");
            entity.Property(e => e.ExtParam)
                .HasMaxLength(100)
                .HasColumnName("extParam");
            entity.Property(e => e.IdDeviceDomainCode).HasColumnName("idDeviceDomainCode");
            entity.Property(e => e.IsCommission).HasColumnName("isCommission");
            entity.Property(e => e.NvrCode)
                .HasMaxLength(100)
                .HasColumnName("nvrCode");
            entity.Property(e => e.OccurNumber).HasColumnName("occurNumber");
            entity.Property(e => e.OccurTime)
                .HasColumnType("datetime")
                .HasColumnName("occurTime");
            entity.Property(e => e.PreviewUrl)
                .HasMaxLength(150)
                .HasColumnName("previewUrl");
            entity.Property(e => e.Reserve)
                .HasMaxLength(100)
                .HasColumnName("reserve");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}